### ISSUE TITLE
Some issues in requirements

### ISSUE THREAD

**Issue by MaiNorapong** [phuwanutj/ku-polls#1]
> 2.&nbsp;User can easily submit a choice on poll items.

The requirements, per instructions, should be testable. *Usability* is a *non-functional requirement* that is not needed here for now. I suggest just focusing on the *functional* part by removing the word "easily".

Two things are still missing: the visibility of the polls before it is open to voting and the time when a user can and can't vote.

Also, can anyone vote? or does being a "user" means they are authenticated? Being more explicit would be helpful for clarity purposes.

**Comment by phuwanutj** [comment]
Fixed. Thank you.
